function Edep = importEdep(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EDEP8 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  EDEP8 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Edep8 = importfile("/Users/Miguel/plan2D/Analitico/ResultadosEdep/Edep-8.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jul-2020 21:16:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "Var5"];
opts.SelectedVariableNames = "VarName4";
opts.VariableTypes = ["string", "string", "string", "double", "string"];
opts = setvaropts(opts, [1, 2, 3, 5], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 5], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Edep8 = readtable(filename, opts);

%% Convert to output type
Edep = table2array(Edep8);
end