function [X, Y, Z, EDep] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [X, Y, Z, EDEP] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [X, Y, Z, EDEP] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [X, Y, Z, EDep] = importfile("/Users/dani/Documents/plan2D/TOPAS/Perfil/Quadrupole/XY/Tests_Dani/Edep_PhantomXY_Q.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2020 17:17:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["X", "Y", "Z", "EDep"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
X = tbl.X;
Y = tbl.Y;
Z = tbl.Z;
EDep = tbl.EDep;
end