%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/dani/Google Drive/Trabajo/UCM/01-Proyectos/20-FLASH/Sims_TOPAS/puntual/1MeV/Fluence.csv
%
% Auto-generated by MATLAB on 12-Dec-2019 12:55:22

% # Results for scorer Fluence
% # R in 100 bins of 0.01 cm
% # Phi in 1 bin  of 360 deg
% # Z in 2000 bins of 0.02 cm
% # Fluence ( /mm2 ) : Sum   

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [9, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["A", "B", "C", "D"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the dat
tblFlu1 = readtable(fullfile('1MeV','Fluence.csv'), opts);
tblEdep1 = readtable(fullfile('1MeV', 'EnergyDep.csv'), opts);

FLU1=tblFlu1.D;
EDEP1=tblEdep1.D;

tblFlu2 = readtable(fullfile('2MeV','Fluence.csv'), opts);
tblEdep2 = readtable(fullfile('2MeV', 'EnergyDep.csv'), opts);

FLU2=tblFlu2.D;
EDEP2=tblEdep2.D;

tblFlu3 = readtable(fullfile('3MeV','Fluence.csv'), opts);
tblEdep3 = readtable(fullfile('3MeV', 'EnergyDep.csv'), opts);

FLU3=tblFlu3.D;
EDEP3=tblEdep3.D;

tblFlu4 = readtable(fullfile('4MeV','Fluence.csv'), opts);
tblEdep4 = readtable(fullfile('4MeV', 'EnergyDep.csv'), opts);

FLU4=tblFlu4.D;
EDEP4=tblEdep4.D;

tblFlu5 = readtable(fullfile('5MeV','Fluence.csv'), opts);
tblEdep5 = readtable(fullfile('5MeV', 'EnergyDep.csv'), opts);

FLU5=tblFlu5.D;
EDEP5=tblEdep5.D;

tblFlu6 = readtable(fullfile('6MeV','Fluence.csv'), opts);
tblEdep6 = readtable(fullfile('6MeV', 'EnergyDep.csv'), opts);

FLU6=tblFlu6.D;
EDEP6=tblEdep6.D;

tblFlu7 = readtable(fullfile('7MeV','Fluence.csv'), opts);
tblEdep7 = readtable(fullfile('7MeV', 'EnergyDep.csv'), opts);

FLU7=tblFlu7.D;
EDEP7=tblEdep7.D;

tblFlu8 = readtable(fullfile('8MeV','Fluence.csv'), opts);
tblEdep8 = readtable(fullfile('8MeV', 'EnergyDep.csv'), opts);

FLU8=tblFlu8.D;
EDEP8=tblEdep8.D;

tblFlu9 = readtable(fullfile('9MeV','Fluence.csv'), opts);
tblEdep9 = readtable(fullfile('9MeV', 'EnergyDep.csv'), opts);

FLU9=tblFlu9.D;
EDEP9=tblEdep9.D;

tblFlu10 = readtable(fullfile('10MeV','Fluence.csv'), opts);
tblEdep10 = readtable(fullfile('10MeV', 'EnergyDep.csv'), opts);

FLU10=tblFlu10.D;
EDEP10=tblEdep10.D;

%FLUENCE AND EDEP arrays


FLU=[FLU1,FLU2,FLU3,FLU4,FLU5,FLU6,FLU7,FLU8,FLU9,FLU10];
EDEP=[EDEP1,EDEP2,EDEP3,EDEP4,EDEP5,EDEP6,EDEP7,EDEP8,EDEP9,EDEP10];

clear opts
clear tblFlu1 tblFlu2 tblFlu3 tblFlu4 tblFlu5 tblFlu6 tblFlu7 tblFlu8 tblFlu9 tblFlu10
clear tblEdep1 tblEdep2 tblEdep3 tblEdep4 tblEdep5 tblEdep6 tblEdep7 tblEdep8 tblEdep9 tblEdep10

clear FLU1 FLU2 FLU3 FLU4 FLU5 FLU6 FLU7 FLU8 FLU9 FLU10
clear EDEP1 EDEP2 EDEP3 EDEP4 EDEP5 EDEP6 EDEP7 EDEP8 EDEP9 EDEP10


