%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/dani/Google Drive/Trabajo/UCM/01-Proyectos/20-FLASH/Sims_TOPAS/puntual/1MeV/Fluence.csv
%
% Auto-generated by MATLAB on 12-Dec-2019 12:55:22

% # Results for scorer Fluence
% # R in 100 bins of 0.01 cm
% # Phi in 1 bin  of 360 deg
% # Z in 2000 bins of 0.02 cm
% # Fluence ( /mm2 ) : Sum   

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [9, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["A", "B", "C", "D"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/Users/Miguel/Documents/GitHub/plan2D/TOPAS/1MeV/Fluence.csv", opts);
tbl2 = readtable("/Users/Miguel/Documents/GitHub/plan2D/TOPAS/1MeV/EnergyDep.csv", opts);

%% Convert to output type
flu = tbl.D;
Edep = tbl2.D;

NR = 100;
NZ = 2000;
dR = 0.01;
dZ = 0.02;
Rvalues = dR*(1:NR) - dR/2;
Zvalues = dZ*(1:NZ) - dZ/2;

flu = reshape(flu, [NZ NR]);
Edep = reshape(Edep, [NZ NR]);

Sflu=[];
SEdep=[];

%Choose the Z range for the Sigma interpolation
a=125;
b=2000;
%Sigma for the fluence

for i=a:b;
    F1 = fit(Rvalues', flu(i,:)', 'gauss1');
    ss=F1.c1;
    Sflu=[Sflu,ss];
end
pflu=polyfit(Zvalues(a:b),Sflu,2);
SfluInterp=polyval(pflu,Zvalues);
figure
plot(Zvalues,SfluInterp)
ylabel('Sigma (cm)')
xlabel('Z (cm)')
title('Fluence')

%Sigma for the Edep

for i=a:b;
    F2 = fit(Rvalues', Edep(i,:)', 'gauss1');
    sse=F2.c1;
    SEdep=[SEdep,sse];
end
pEdep=polyfit(Zvalues(a:b),SEdep,2);
SEdepInterp=polyval(pEdep,Zvalues);
figure
plot(Zvalues,SEdepInterp)
ylabel('Sigma (cm)')
xlabel('Z (cm)')
title('Energy deposition')

