%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/dani/Google Drive/Trabajo/UCM/01-Proyectos/20-FLASH/Sims_TOPAS/puntual/1MeV/Fluence.csv
%
% Auto-generated by MATLAB on 12-Dec-2019 12:55:22

% # Results for scorer Fluence
% # R in 100 bins of 0.01 cm
% # Phi in 1 bin  of 360 deg
% # Z in 2000 bins of 0.02 cm
% # Fluence ( /mm2 ) : Sum   

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [9, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["A", "B", "C", "D"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/Users/dani/Google Drive/Trabajo/UCM/01-Proyectos/20-FLASH/Sims_TOPAS/puntual/4MeV/Fluence.csv", opts);
tbl2 = readtable("/Users/dani/Google Drive/Trabajo/UCM/01-Proyectos/20-FLASH/Sims_TOPAS/puntual/4MeV/EnergyDep.csv", opts);

%% Convert to output type
R = tbl.A;
Z = tbl.C;
flu = tbl.D;
Edep = tbl2.D;

NR = 100;
NZ = 2000;
dR = 0.01;
dZ = 0.02;
Rvalues = dR*(1:NR) - dR/2;
Zvalues = dZ*(1:NZ) - dZ/2;

Rres = reshape(R, [NZ NR]);
Zres = reshape(Z, [NZ NR]);
flu = reshape(flu, [NZ NR]);
Edep = reshape(Edep, [NZ NR]);

%% Clear temporary variables
clear opts tbl R Z Rres Zres tbl2

%% Analysis
DDD = sum(Edep,2);       % Para energía (no dosis), basta con sumar
fluZ = sum(flu.*Rmat,2); % Para fluencia como es /mm2, hay que hacer integral radial
sigmaZ = nan(NZ,1);

% Find sigma
for i=1:NZ
    sliceFlu = flu(i, :);
    F1 = fit(Rvalues', sliceFlu', 'gauss1', 'Lower', [0 0 0], 'Upper', [1e6 0 2]);
    sigmaZ(i) = F1.c1 / sqrt(2);
    i
end